title: Qin's blog
author: Qin
description: Place to write for Qin.

highlighter: null
permalink: /:title

url:
baseurl:

color_scheme: amber
# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
